development:
  adapter: redis3.20
  #ici c'est redis qu'il faut installer, pas autre chose comme indqiué dans le cours qui n'est pas à jour!

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: StoryTime_production
